//-----------------------------------------------------------------------
// <copyright file="DevTuningfork.cs" company="Google">
//
// Copyright 2020 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>
//-----------------------------------------------------------------------

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dev_tuningfork.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Android.PerformanceParameters {

  /// <summary>Holder for reflection information generated from dev_tuningfork.proto</summary>
  public static partial class DevTuningforkReflection {

    #region Descriptor
    /// <summary>File descriptor for dev_tuningfork.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DevTuningforkReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRkZXZfdHVuaW5nZm9yay5wcm90byJJCgpBbm5vdGF0aW9uEiQKDWxvYWRp",
            "bmdfc3RhdGUYASABKA4yDS5Mb2FkaW5nU3RhdGUSFQoFc2NlbmUYAiABKA4y",
            "Bi5TY2VuZSInCg5GaWRlbGl0eVBhcmFtcxIVCg1xdWFsaXR5X2xldmVsGAEg",
            "ASgFKmAKDExvYWRpbmdTdGF0ZRIYChRMT0FESU5HU1RBVEVfSU5WQUxJRBAA",
            "EhwKGExPQURJTkdTVEFURV9OT1RfTE9BRElORxABEhgKFExPQURJTkdTVEFU",
            "RV9MT0FESU5HEAIqcAoFU2NlbmUSEQoNU0NFTkVfSU5WQUxJRBAAElQKUFND",
            "RU5FX0FTU0VUU19HT09HTEVfQU5EUk9JRF9QRVJGT1JNQU5DRVBBUkFNRVRF",
            "UlNfSU5URVJOQUxfU0FNUExFX1NDRU5FU19ERUZBVUxUEAFCJ6oCJEdvb2ds",
            "ZS5BbmRyb2lkLlBlcmZvcm1hbmNlUGFyYW1ldGVyc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Android.PerformanceParameters.LoadingState), typeof(global::Google.Android.PerformanceParameters.Scene), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Android.PerformanceParameters.Annotation), global::Google.Android.PerformanceParameters.Annotation.Parser, new[]{ "LoadingState", "Scene" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Android.PerformanceParameters.FidelityParams), global::Google.Android.PerformanceParameters.FidelityParams.Parser, new[]{ "QualityLevel" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum LoadingState {
    [pbr::OriginalName("LOADINGSTATE_INVALID")] Invalid = 0,
    [pbr::OriginalName("LOADINGSTATE_NOT_LOADING")] NotLoading = 1,
    [pbr::OriginalName("LOADINGSTATE_LOADING")] Loading = 2,
  }

  public enum Scene {
    [pbr::OriginalName("SCENE_INVALID")] Invalid = 0,
    [pbr::OriginalName("SCENE_ASSETS_GOOGLE_ANDROID_PERFORMANCEPARAMETERS_INTERNAL_SAMPLE_SCENES_DEFAULT")] AssetsGoogleAndroidPerformanceparametersInternalSampleScenesDefault = 1,
  }

  #endregion

  #region Messages
  public sealed partial class Annotation : pb::IMessage<Annotation> {
    private static readonly pb::MessageParser<Annotation> _parser = new pb::MessageParser<Annotation>(() => new Annotation());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Annotation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Android.PerformanceParameters.DevTuningforkReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Annotation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Annotation(Annotation other) : this() {
      loadingState_ = other.loadingState_;
      scene_ = other.scene_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Annotation Clone() {
      return new Annotation(this);
    }

    /// <summary>Field number for the "loading_state" field.</summary>
    public const int LoadingStateFieldNumber = 1;
    private global::Google.Android.PerformanceParameters.LoadingState loadingState_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Android.PerformanceParameters.LoadingState LoadingState {
      get { return loadingState_; }
      set {
        loadingState_ = value;
      }
    }

    /// <summary>Field number for the "scene" field.</summary>
    public const int SceneFieldNumber = 2;
    private global::Google.Android.PerformanceParameters.Scene scene_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Android.PerformanceParameters.Scene Scene {
      get { return scene_; }
      set {
        scene_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Annotation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Annotation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoadingState != other.LoadingState) return false;
      if (Scene != other.Scene) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoadingState != 0) hash ^= LoadingState.GetHashCode();
      if (Scene != 0) hash ^= Scene.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoadingState != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LoadingState);
      }
      if (Scene != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Scene);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoadingState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LoadingState);
      }
      if (Scene != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Scene);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Annotation other) {
      if (other == null) {
        return;
      }
      if (other.LoadingState != 0) {
        LoadingState = other.LoadingState;
      }
      if (other.Scene != 0) {
        Scene = other.Scene;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            loadingState_ = (global::Google.Android.PerformanceParameters.LoadingState) input.ReadEnum();
            break;
          }
          case 16: {
            scene_ = (global::Google.Android.PerformanceParameters.Scene) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FidelityParams : pb::IMessage<FidelityParams> {
    private static readonly pb::MessageParser<FidelityParams> _parser = new pb::MessageParser<FidelityParams>(() => new FidelityParams());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FidelityParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Android.PerformanceParameters.DevTuningforkReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FidelityParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FidelityParams(FidelityParams other) : this() {
      qualityLevel_ = other.qualityLevel_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FidelityParams Clone() {
      return new FidelityParams(this);
    }

    /// <summary>Field number for the "quality_level" field.</summary>
    public const int QualityLevelFieldNumber = 1;
    private int qualityLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QualityLevel {
      get { return qualityLevel_; }
      set {
        qualityLevel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FidelityParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FidelityParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QualityLevel != other.QualityLevel) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QualityLevel != 0) hash ^= QualityLevel.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QualityLevel != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QualityLevel);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QualityLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QualityLevel);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FidelityParams other) {
      if (other == null) {
        return;
      }
      if (other.QualityLevel != 0) {
        QualityLevel = other.QualityLevel;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            QualityLevel = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
